apiVersion: apps/v1 
kind: Deployment
metadata:
  name: "{{ .Values.name }}"
  namespace: managedcare-dev
spec: 
  selector:
    matchLabels:
      app: "{{ .Values.label }}"
  replicas: {{ .Values.replicaCount }}
  template: 
    metadata:
      name: "{{ .Values.podname }}"
      namespace: hrxcms
      labels:
        app: "{{ .Values.label }}"
    spec:
      containers:
      - name: "{{ .Values.containerName }}"
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.containerPort }}
