apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: "{{ .Values.appName }}-db-url-secret"
  namespace: "{{ .Values.namespace }}"
spec:
  vault:
    name: "{{ .Values.keyVaultName }}"
    object:
      type: secret
      name: idmoduledburl
---
apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: "{{ .Values.appName }}-consent-token-private-key"
  namespace: "{{ .Values.namespace }}"
spec:
  vault:
    name: "{{ .Values.keyVaultName }}"
    object:
      type: secret
      name: consent-token-private-key
---
apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: "{{ .Values.appName }}-consent-token-public-key"
  namespace: "{{ .Values.namespace }}"
spec:
  vault:
    name: "{{ .Values.keyVaultName }}"
    object:
      type: secret
      name: consent-token-public-key
---
apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: "{{ .Values.appName }}-id-module-blob-connection"
  namespace: "{{ .Values.namespace }}"
spec:
  vault:
    name: "{{ .Values.keyVaultName }}"
    object:
      type: secret
      name: id-module-blob-connection
---
apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: "{{ .Values.appName }}-clevertap-account-id"
  namespace: "{{ .Values.namespace }}"
spec:
  vault:
    name: "{{ .Values.keyVaultName }}"
    object:
      type: secret
      name: clevertap-account-id
---
apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: "{{ .Values.appName }}-clevertap-password"
  namespace: "{{ .Values.namespace }}"
spec:
  vault:
    name: "{{ .Values.keyVaultName }}"
    object:
      type: secret
      name: clevertap-password
{{ if (.Values.insightsSecretName) }}
---
apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: "{{ .Values.appName }}-azure-insights-key"
  namespace: "{{ .Values.namespace }}"
spec:
  vault:
    name: "{{ .Values.keyVaultName }}"
    object:
      type: secret
      name: {{ .Values.insightsSecretName }}
{{ end }}