trigger:
- develop

resources:
- repo: self

pool:
  vmImage: 'ubuntu-18.04'

jobs:
- job: automated_pipeline
  displayName: Quality checks + Quality Analysis + Deployment
  pool: CI Pool
  steps:
  # - task: CmdLine@2
  #   inputs:
  #     script: |
  #       npm i
  #       npm run lint
  #       npm run test:azure
  # - task: PublishTestResults@2
  #   inputs:
  #     testResultsFormat: 'JUnit'
  #     testResultsFiles: 'test-results.xml'
  # - task: PublishCodeCoverageResults@1
  #   inputs:
  #     codeCoverageTool: 'Cobertura'
  #     summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml'
  #     reportDirectory: '$(System.DefaultWorkingDirectory)/coverage'
  # - task: SonarQubePrepare@4
  #   inputs:
  #     SonarQube: 'Sonarqube Server'
  #     scannerMode: 'CLI'
  #     configMode: 'file'
  #     configFile: 'sonar-project-dev.properties'
  # - task: SonarQubeAnalyze@4
  - task: Docker@2
    inputs:
      containerRegistry: 'bfhl-acr-connection'
      repository: 'HRx-CMS'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      tags: '$(Build.BuildId)'
  - task: HelmInstaller@1
    inputs:
      helmVersionToInstall: '3.1.1'
  - task: HelmDeploy@0
    inputs:
      connectionType: 'Kubernetes Service Connection'
      kubernetesServiceConnection: 'bfhl-aks-dev'
      command: 'upgrade'
      chartType: 'FilePath'
      chartPath: './deployment/helm-chart'
      releaseName: 'identity'
      overrideValues: 'version=$(Build.BuildId)'
      valueFile: './deployment/helm-chart/values-dev.yaml'
  - task: HelmDeploy@0
    inputs:
      connectionType: 'Kubernetes Service Connection'
      kubernetesServiceConnection: 'bfhl-aks-dev'
      command: 'upgrade'
      chartType: 'FilePath'
      chartPath: './deployment/helm-chart'
      releaseName: 'identity-open'
      overrideValues: 'appName=identity-open,version=$(Build.BuildId),disableAuth=true'
      valueFile: './deployment/helm-chart/values-dev.yaml'
